sudo: false
language: java
env:
  global:
    - # GITHUB_TOKEN
    - secure: "fJw3Nnh2up/JMEaYIRc/patBxsH0xh6OVrqQ2kfh6iox005GNs/8sZNl78lN/XLpUO0YM6vfU+1sLEKZzXc9GjO5VfxLeFMOENJpGU3h5DANq8IBM5lojutfUvCK+1Wt5zTIVgTmHl5OgfvdPQl8rCucVfIcr7HtIyVvUJMSrTAnYoWcROi4qzkbc2grzGDE0G6MjPYQfT4ZZvktoPx6Ul9W9iENPbQQjUZPB4WXIbH6SYUZFUF2BIzHQt4xj5cAlNvhu+diw6kC5rtgmwvLFgaz02hO3TvPf6qCtcEeJJeTm1W/Up+Dr2AfHOc6W1KqVYkkS4v1ffew/UzPiTl+5KDGtbZDtSfelDgwTPzdyxfFmYeEnM9CeQlbUZUs9+p/0Kqd8EcEYV6yi13YRfNLypz5AvRYS6FVNhESWVjqaUnVeuDNotZcAF7YMl2xJjmdyGWOKG548PMzvBC50qgNCjVeggALG8hPmzu+9n/RjQURImcuCyRVNDHEXAJKYO8lvsHmsUeYW1zs+ZmYeRPwA4dC7z0sUMelUFG4EM2UOXR+6+s8XbHXsAlEEHe3EglVFtG02wH8xk7XvgJqJHiN6cWk6aa42za/MJDp9i1gW1yZ/45ZKvUNlnFklb3tgdMNUrjlMKE59y0TFPzEIRJjAqrlmgcBMnkrc6kBqDQUNk8="
    - # GRADLE_PUBLISH_KEY
    - secure: "OLD5X8UzDB83G87C8w5MJ7dnEaeRASWJBgAO6nM3uwghq9/gmXgReQFHfLkYe/Zqw6JrOW71+2Z7WbpGq/fIyk96BzRxrNBtyWSiYiB0G3YNnyjOFZgnWFrWPDv3Xmoplf5a0pUAxwpQsSUksDnJq6Dl3S1uzqUNCbPZ/n1pV8BssEASSE9twXr8lDFAGGOAOszJ5Z5f5jeQ6ZtxewT9TXg6VeGbC7tF3Dm/Y5/ZZPXMgbmDfm0vAOAJDKYe80MHp0M9PLdzeN1b/jQYPsBCp++t2OlUfmRsTC4drt8Ug2ZXq1EjgfIGy8ba6PAxgX4MpHub+NWBIKqlP7eQSfUsDHbaWPMY/fRPjHp+2iZL7bPK2SqgKYhVpS5Uor4R2aVacZ7e8kD5PKNd64KxwPGQgrAm3qP1MRfSuYLIozju9rJ5ZRUE1bM3RAtUdreanbwQUvdbMiP/FjQbqzfkB1me/Yhac14ZjiZgixjyFCVLkJBQyoebx6OqzCbGer9jIZf7fuO28FG2fpBNfTYweRIU6IdjpWO8gZLLs4Z9do+laOKj3in7znDRA51cDnUl7b8rq0JxqTshXjStJltjSHKKwAxnm4/ekUQiD7tyFpjo9IiAit/Yqw00Gt1zqShqBOu/6OuAXCgQweWpI1qQohtyQh+wrEbR02Qeznibu7SG87M="
    - # GRADLE_PUBLISH_SECRET
    - secure: "mHRmHY1SkYa5VeU1lJyn7K+a4mf+sVQnSN88bEDsrcZTGaZrHsR4tpBWi+FYCvwY19ZpbDc1EY/MudGas1UnG3SLHiqNYrj3G6ioSUWRrgbuZ/1bFdKo4CnMJMctf6YP9ac+hD4NpUcYRgiOVOd52WQaFj9csEZKIbOd4rLeWVO7SR84ecxyWJyNb7kK7VT0VnXd6j4SA1XrymztwVYSE24kJLArg8n8bMgaNSNqP0NS77fKWKna2kJywu4yZycBU5gF4zmMMwusJMSUYX/eszANbW2awTKL8qiMVCT9uBkbdmatW+doaTb5qRaqjOQtnmOOi1WNOkfl7qZQ7MRGKN7GCsztZxTIhLaG/Hfr0e+N3ipKZT8oiYg/3B5OHNU1/jl6vL50AMVpWDH4WFPOV/wqwKK9kmjzpisO4Zkfz4S3D3TTjFwp/psLkdd3cYpmZNrHDfldsn4Y1uWp85bfy8SFl0/yzVQZo0zqvJVKcEC4W3bsukyDM+j7EhEI8CW7C0sXAlYEtYaqYjy7bPzGkmE4SuzARo6By2Y/5FcVH2+9I0k2QPPPdv1hvsZPRVNFcV4aQbjP5repfGlBIw5ZtFxYQzCgOgPEyvKF4xvty5htK5rhUyZK5hH7PCRJa9h4U2WQVqxLYe7z0hNKJj/TwPNoOlOzvC8G/J+/V/ivKIY="

jdk:
  - openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: skip

before_script:
  - ./gradlew check

script: |-
  [ "${TRAVIS_PULL_REQUEST}" = "false" ] && source ci/setup-git.sh && ./gradlew release -Dorg.ajoberstar.grgit.auth.username=${GITHUB_TOKEN} -Dorg.ajoberstar.grgit.auth.password -Dgradle.publish.key=${GRADLE_PUBLISH_KEY} -Dgradle.publish.secret=${GRADLE_PUBLISH_SECRET} --info --stacktrace

notifications:
  email:
    on_success: never
    on_failure: never
